#!/bin/bash
# embed-pef.sh <input.pef> <output.r> <resType> <resID>
# Hex-encode a PEF (or any binary) into a Rez 'data' resource so an app can
# GetResource it and hand it to InstallDriverFromMemory.
set -eu
IN="$1"; OUT="$2"; TYPE="${3:-sPEF}"; ID="${4:-128}"
[ -f "$IN" ] || { echo "embed-pef: missing $IN" >&2; exit 1; }
{
  echo "/* auto-generated by embed-pef.sh from $(basename "$IN") */"
  echo "data '$TYPE' ($ID, \"SiI3512 driver PEF\") {"
  # 16 bytes (32 hex chars) per line, each wrapped as  $"....."
  xxd -p -c 16 "$IN" | sed 's/^/    $"/; s/$/"/'
  echo "};"
} > "$OUT"
echo "embed-pef: wrote $OUT ($(wc -c < "$IN") bytes as '$TYPE' $ID)"
